---
inherit_from: .rubocop_todo.yml

inherit_gem:
  voxpupuli-rubocop: rubocop.yml

# Disabled
Layout/LineLength:
  Max: 200

Lint/RedundantCopDisableDirective:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false
